Check for md5 command and use what is present

diff --git a/fritzbox-config-downloader b/fritzbox-config-downloader
--- a/fritzbox-config-downloader
+++ b/fritzbox-config-downloader
@@ -147,7 +147,17 @@ elif [ "${SID}" = "0000000000000000" ]; then # 16 zeros
 		exit 2
 	fi
 
-	response=$(printf "${challenge}-${password}" | iconv -f utf-8 -t utf-16le | openssl dgst -md5 | sed 's/(stdin)=//g' | sed 's/ *//g')
+	if hash md5sum 2>/dev/null; then
+		md5command = "md5sum -b"
+	elif hash md5 2>/dev/null; then
+		md5command = "md5"
+	elif hash openssl 2> /dev/null; then
+		md5command = "openssl dgst -md5"
+	else
+		echo "Missing dependency! Please make sure that one of the following commands is installed on your system: md5sum, md5 or openssl"
+		exit 1
+	fi
+	response=$(printf "${challenge}-${password}" | iconv -f utf-8 -t utf-16le | ${md5command} | sed 's|^.* ||g')
 	case "${loginType}" in
 		1) login=$($curlCmd -d "login:command/response=${challenge}-${response}" -d "getpage=../html/login_sid.xml" "${host}/cgi-bin/webcm") ;;
 		2) login=$($curlCmd -d "response=${challenge}-${response}" -d "username=${username}" "${host}/login_sid.lua") ;;
