fixed getopt compatibility

diff --git a/fritzbox-config-downloader b/fritzbox-config-downloader
--- a/fritzbox-config-downloader
+++ b/fritzbox-config-downloader
@@ -4,13 +4,31 @@
 print_usage() {
 	echo "Usage: ${0} [arguments]"
 	echo "Arguments:"
-	echo "-h, --host HOST\t\tThe host of the Fritz!Box.\t\tDefaults to fritz.box"
-	echo "-u, --username USERNAME\t\tThe username for the Fritz!Box.\t\tDefault is no username"
-	echo "-p, --password PASSWORD\t\tThe password for the Fritz!Box.\t\tDefault is no password"
-	echo "-e, --export-password=PASSWORD\t\tThe password for the backup file.\t\tDefault is admin. If the argument is not present, no password will be used"
-	echo "-o, --output-file OUTPUT_FILE\t\tThe downloaded backup will be written to this file.\t\tDefault is FritzBox.export"
-	echo "-r, --remote\t\tUse remote access to connect to the Fritz!Box"
-	echo "-s, --second-password\t\tSecond password for older Fritz!OS versions.\t\tDefault is no password"
+	temp=$(getopt -T)
+	if [ $? -eq 4 ]; then
+		hostArg="-h, --host"
+		usernameArg="-u, --username"
+		passwordArg="-p, --password"
+		exportPasswordArg="-e, --export-password"
+		outputFileArg="-o, --output-file"
+		remoteArg="-r, --remote"
+		secondPasswordArg="-s, --second-password"
+	else
+		hostArg="-h"
+		usernameArg="-u"
+		passwordArg="-p"
+		exportPasswordArg="-e"
+		outputFileArg="-o"
+		remoteArg="-r"
+		secondPasswordArg="-s"
+	fi
+	echo "${hostArg} HOST\t\t\tThe host of the Fritz!Box.\t\t\t\tDefaults to fritz.box."
+	echo "${usernameArg} USERNAME\t\tThe username for the Fritz!Box.\t\t\t\tDefault is no username."
+	echo "${passwordArg} PASSWORD\t\tThe password for the Fritz!Box.\t\t\t\tDefault is no password."
+	echo "${exportPasswordArg}[=PASSWORD]\tThe password for the backup file.\t\t\tDefault is admin. If the argument is not present, no password will be used."
+	echo "${outputFileArg} OUTPUT_FILE\tThe downloaded backup will be written to this file.\tDefault is FritzBox.export."
+	echo "${remoteArg}\t\t\tUse remote access to connect to the Fritz!Box."
+	echo "${secondPasswordArg}\t\tSecond password for older Fritz!OS versions.\t\tDefault is no password."
 }
 
 # Set some defaults
@@ -23,12 +41,22 @@ remoteAccess=0
 secondPassword=""
 
 # Parse the arguments
-ARGS=`getopt -o 'h:u:p:e::o:rs:' --long 'host:,username:,password:,export-password::,output-file:,remote,second-password:,help' -n "${0}" -- "$@"`
-eval set -- "${ARGS}"
+temp=$(getopt -T)
+if [ $? -eq 4 ]; then
+	args=`getopt -o h:u:p:e::o:rs: --long "host:,username:,password:,export-password::,output-file:,remote,second-password:,help" -n 'fritzbox-config-downloader' -- $*`
+else
+	args=`getopt h:u:p:e::o:rs: -- $*`
+fi
+if [ $? -ne 0 ]; then
+	echo "Invalid arguments!"
+	print_usage
+	exit 1
+fi
+eval set -- "${args}"
 
 # Extract the parsed arguments
-while true ; do
-	case "${1}" in
+for i ; do
+	case "${i}" in
 		-h|--host)
 			case "${2}" in
 				"") shift 2 ;;
@@ -60,9 +88,9 @@ while true ; do
 				"") shift 2 ;;
 				*) secondPassword=$2 ; shift 2 ;;
 			esac ;;
-		--help) print_usage ; shift ;;
+		--help) print_usage ; exit 0 ;;
 		--) shift ; break ;;
-		*) echo "Unkown argument ${1}!" ; exit 1 ;;
+		*) echo "Unknown argument ${1}!" ; exit 1 ;;
 	esac
 done
 
